version: '3.8'


services:
  backend-gateway-service:
    image: backend-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - postgres
    networks:
      - learn2grow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]